INSERT INTO public.legal_doc_templates (clinic_id, slug, name, doc_type, content, trigger_status, is_active)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'tcle-procedimento',
  'TCLE - Termo de Consentimento Livre e Esclarecido',
  'procedimento',
  E'<h2 style="text-align:center">TERMO DE CONSENTIMENTO LIVRE E ESCLARECIDO (TCLE)</h2>\n\n<h3>1. IDENTIFICACAO DO PACIENTE</h3>\n<p><strong>Nome:</strong> {{nome}}<br>\n<strong>CPF:</strong> {{cpf}}<br>\n<strong>Data de nascimento:</strong> {{data_nascimento}}<br>\n<strong>Endereco:</strong> {{endereco_paciente}}</p>\n\n<h3>2. IDENTIFICACAO DO PROFISSIONAL</h3>\n<p><strong>Nome:</strong> {{profissional}}<br>\n<strong>Registro:</strong> {{registro_profissional}}<br>\n<strong>Especialidade:</strong> {{especialidade}}</p>\n\n<h3>3. PROCEDIMENTO(S) REALIZADO(S)</h3>\n<p>{{lista_procedimentos}}</p>\n\n{{blocos_procedimentos}}\n\n<hr style="margin:24px 0;border:none;border-top:2px solid #374151">\n\n<h3>PRIVACIDADE E PROTECAO DE DADOS (LGPD)</h3>\n<ul>\n<li>Autorizo o tratamento dos meus dados pessoais para fins de registro e acompanhamento clinico, conforme a Lei n 13.709/2018 (LGPD);</li>\n<li>Permito o armazenamento dos meus dados em um sistema seguro, com acesso restrito.</li>\n</ul>\n\n<h3>INFORMACOES FINANCEIRAS</h3>\n<ul>\n<li>Fui informado(a) sobre o custo total do procedimento;</li>\n<li>Recebi esclarecimentos sobre formas de pagamento, politica de cancelamento e reembolso.</li>\n</ul>\n\n<h3>DIREITOS DO PACIENTE</h3>\n<ul>\n<li>Direito a informacoes claras e objetivas;</li>\n<li>Direito a esclarecer duvidas a qualquer momento antes do procedimento;</li>\n<li>Direito de obter copia deste termo;</li>\n<li>Direito de retirar o consentimento ate a aplicacao.</li>\n</ul>\n\n<h3>BASE LEGAL</h3>\n<ul>\n<li>Codigo de Etica Medica - Art. 46</li>\n<li>Codigo de Defesa do Consumidor - Art. 6, III</li>\n<li>Lei n 13.709/2018 (LGPD)</li>\n<li>Codigo Civil - Art. 15</li>\n<li>Recomendacao CFM n 1/2016</li>\n</ul>\n\n<h3>DECLARACAO DO(A) PACIENTE</h3>\n<p>Declaro que:</p>\n<ul>\n<li>Recebi explicacoes claras sobre finalidade, descricao, riscos, beneficios, contraindicacoes e alternativas;</li>\n<li>Compreendo a natureza temporaria do resultado e a necessidade de reaplicacoes;</li>\n<li>Estou ciente dos meus direitos e autorizo, de forma livre e esclarecida, a realizacao do(s) procedimento(s).</li>\n</ul>\n\n<p style="text-align:center">{{endereco_clinica}}, {{data_extenso}}</p>\n\n<p style="text-align:center"><br>________________________________________<br><strong>{{nome}}</strong><br>PACIENTE</p>\n\n<p style="text-align:center"><br>________________________________________<br><strong>{{profissional}}</strong><br>{{especialidade}}</p>\n\n<p style="text-align:center;font-size:10px;color:#9CA3AF;margin-top:24px">Este documento sera arquivado no prontuario do paciente por, no minimo, 20 anos, conforme legislacao vigente.</p>',
  'na_clinica',
  true
) ON CONFLICT (clinic_id, slug) DO UPDATE SET
  content = EXCLUDED.content,
  name = EXCLUDED.name,
  trigger_status = EXCLUDED.trigger_status;
