INSERT INTO quiz_templates (clinic_id, slug, title, kanban_target, pipeline, active, schema) VALUES ('00000000-0000-0000-0000-000000000001', 'lifting-5d', 'Protocolo Lifting 5D', 'kanban-fullface', 'evolution', true, '{"intro":{"title":"PROTOCOLO LIFTING 5D","description":"Rejuvenesca ate 15 anos naturalmente sem cirurgia plastica

Conheca o Novedoso Protocolo de Harmonizacao e Reconciliacao Facial que esta devolvendo a autoconfianca de mulheres de 40 a 65 anos em Maringa

Resultados naturais. Sem exageros. Sem perder sua Identidade.

Responda umas perguntas rapidas para descobrir se voce e candidata ideal","cta_label":"COMECAR MINHA AVALIACAO GRATUITA","image_url":"","logo_url":""},"questions":[{"title":"O Protocolo Lifting 5D trabalha nas 5 DIMENSOES do rejuvenescimento facial","description":"1 - Sustentacao Estrutural
2 - Estimulo de Colageno
3 - Definicao de Contorno
4 - Hidratacao Profunda
5 - Rejuvenescimento Celular

Desenvolvido exclusivamente para mulheres acima de 40 anos que querem reconquistar a confianca ao se olhar no espelho.","type":"single_choice","required":true,"options":[{"label":"Sim\! E exatamente isso que eu preciso","score":2},{"label":"Quero resultados como esses","score":2}]},{"title":"Perfeito\! Vamos comecar sua avaliacao personalizada
Como posso te chamar?","type":"contact_name","required":true},{"title":"A Dra. Mirian analisa pessoalmente cada avaliacao antes de liberar o agendamento da consulta.","description":"Seus dados estao 100% protegidos - nao compartilhamos com terceiros.","type":"single_choice","required":true,"options":[{"label":"Ok, entendi","score":0}]},{"title":"Otimo, {nome}\! Quando voce se olha no espelho, quais sao os sinais que mais te incomodam no rosto?","description":"Pode marcar varias opcoes:","type":"multiple_choice","required":true,"options":[{"label":"Rugas na testa","score":0},{"label":"Pe de galinha","score":0},{"label":"Olheiras profundas","score":0},{"label":"Bigode chines (sulcos nasolabiais)","score":0},{"label":"Nariz (ponta caida)","score":0},{"label":"Codigo de barras (ao redor da boca)","score":0},{"label":"Labios desidratados ou finos","score":0},{"label":"Flacidez facial geral","score":0},{"label":"Flacidez de palpebras","score":0},{"label":"Flacidez na papada (queixo duplo)","score":0},{"label":"Cicatrizes de acne","score":0},{"label":"Assimetria facial","score":0},{"label":"Perda de definicao no contorno do rosto","score":0},{"label":"Outro","score":0}]},{"title":"Entendi, {nome}. O quanto essas questoes estao afetando sua autoestima e confianca no dia a dia?","type":"scale","required":true,"scale_min_label":"Nao me incomoda","scale_max_label":"Me incomoda muito"},{"title":"Por que o Lifting 5D nao e um procedimento qualquer","description":"O Lifting 5D reune tecnologia avancada e entrega resultados em ate 3 horas - ate 15 anos de rejuvenescimento facial - nao sendo indicado para quem busca solucoes simples ou superficiais.

Ele comeca com uma consulta criteriosa, onde a Dra. Mirian de Paula analisa o rosto como um todo e define se faz sentido para voce seguir com o protocolo ou nao.","type":"single_choice","required":true,"options":[{"label":"Estou pronta para rejuvenescer","score":3},{"label":"Preciso me priorizar","score":2}]},{"title":"Muito bem, {nome}.","description":"Faltam apenas 3 perguntas rapidas para finalizarmos sua avaliacao.

Ao concluir, voce desbloqueia um bonus especial para ja iniciar seus cuidados de rejuvenescimento facial na mesma consulta com a Dra. Mirian.","type":"single_choice","required":true,"options":[{"label":"Vamos continuar\!","score":0}]},{"title":"Quando voce pensa em rejuvenescimento facial, o que faz mais sentido para voce hoje?","type":"single_choice","required":true,"options":[{"label":"Priorizar menor custo, mesmo que os resultados sejam mais limitados","score":0},{"label":"Investir de forma justa em tecnologias que entregam resultados duradouros e naturais","score":3}]},{"title":"Vou te explicar como funciona a consulta de avaliacao, {nome}\!","description":"Seu plano de rejuvenescimento com o Protocolo Lifting 5D sera construido junto com voce, em uma Consulta de Avaliacao com duracao aproximada de 1 hora - valor de R$200 (abatido nos protocolos que voce fechar no dia).

A Dra. Mirian avalia seu rosto, suas principais queixas e prioridades, e juntas definimos o melhor caminho para resultados seguros, naturais e elegantes.

Voce deseja seguir para o agendamento?","type":"single_choice","required":true,"options":[{"label":"Sim, quero agendar","score":3},{"label":"Quero receber mais informacoes","score":1}]},{"title":"Perfeito, {nome}\! Qual e o melhor numero para alguem da minha equipe entrar em contato com voce?","description":"Nao esqueca de perguntar para a secretaria qual e o Bonus Especial que voce ganha ao agendar sua avaliacao\!","type":"contact_phone","required":true}],"scoring":{"hot":{"min":11},"warm":{"min":6},"cold":{"min":0}},"outro":{"title":"Parabens, {nome}\!","message":"Sua avaliacao foi enviada com sucesso\!

Voce ja deu o primeiro passo e agora vem a melhor parte. As mulheres que escolhem se cuidar na Clinica Mirian de Paula tem um perfil especial: sao exigentes, decididas e apaixonadas por resultados de verdade.

Elas entendem que o Lifting 5D e o unico protocolo nao cirurgico que garante rejuvenescimento facial natural e duradouro, sem promessas vazias.

VOCE TEM 2 OPCOES AGORA:
1 - Aguardar o contato da nossa equipe (em ate 24h)
2 - Garantir PRIORIDADE TOTAL agendando agora e desbloqueando seu Bonus Especial","wa_phone":"","wa_message":"Ola\! Acabei de responder o quiz Lifting 5D e quero garantir prioridade no agendamento com meu Bonus Especial\!","btn_label":"QUERO PRIORIDADE + MEU BONUS","btn_url":"","btn_color":"#111111","btn_text_color":"#ffffff","video_url":"","video_autoplay":true,"image_url":""},"appearance":{"primary_color":"#6366F1","cover_fit":"cover"}}'::jsonb) ON CONFLICT (slug) DO UPDATE SET schema = EXCLUDED.schema, title = EXCLUDED.title, active = EXCLUDED.active, updated_at = now();
